"""Layered FCHL golden parity tests (plan todo 36; gap investigation §10.2/§10.3 trial A).

Layer-by-layer comparison against a frozen golden produced from the
``dp5@b6cf559007a5d13fe79654f37daf945ee1661a23`` assets checked into
``src/acp/nmr/models/`` so a failure in one layer cannot be masked by a
"close enough" final probability (gap §10.2: 不能为了让最终概率相近而掩盖
descriptor/kernel 层的系统差异):

1. **descriptor** — :func:`acp.nmr.fchl.build_atom_representations` for a fixed
   ethanol geometry (two carbon atoms) vs frozen ``(5, 86)`` arrays.
2. **kernel** — :func:`acp.nmr.fchl.get_atomic_kernels_numpy` (pure-numpy port
   of the compiled Fortran reference) vs frozen kernels; when ``qml`` is
   importable the compiled-kernel parity layer also runs against the same
   frozen numpy golden (skipped with an explicit ``NOT_VERIFIED`` reason when
   absent — no stub ever stands in for the compiled kernel).
3. **weighted KDE** — :func:`acp.nmr.fchl.atom_probability_fchl` on the full
   checked-in ``folded_scaled_errors.p`` residual set with *fixed* weights
   (the kernel seam is pinned, so this layer is independent of kernel-layer
   correctness), plus the ``sum(K_sim) == 0`` unweighted fallback.
4. **candidate probability** — the public ``GoodmanDP5Model`` seams
   ``probability_per_conformer`` / ``probability`` on the full checked-in
   assets, and ``probability_per_conformer_fchl`` on a pinned slice of the
   training set (runtime note below).

Runtime note (why layer 4's FCHL path slices the training set): the pure-numpy
kernel costs ~28 ms per training atom, i.e. ~25 min per query atom against the
full 53 208-atom ``atomic_reps.gz``.  The FCHL candidate layer therefore runs
on the first ``FCHL_REDUCED_TRAIN_SLICE`` training atoms and the first
``2 * FCHL_REDUCED_TRAIN_SLICE`` folded residuals (the 2x fold pairing is
preserved exactly; the KDE-rescale assets are reused verbatim).  The slicing is
deterministic and derived from the NOTICE-pinned assets; layer 2 anchors the
real kernel and layer 3 anchors the real KDE on the full residual set, so no
scientific information is silently dropped — the full-fat FCHL call is
recorded as out of unit-test budget, not as verified.

Tolerances are frozen in ``tests/baseline/nmr/fchl_golden_tolerances.json``
after measuring real repeatability (in-process repeats and fresh-process
regeneration were bit-identical; see the ``measurement`` block in that file).
The golden itself is generated by
``tests/baseline/nmr/generate_fchl_goldens.py``, which imports
:func:`compute_layer_values` from this module so the committed golden and the
assertions can never drift into two implementations.  Regenerate with:

    PYTHONPATH=src python3.11 tests/baseline/nmr/generate_fchl_goldens.py

Do not relax a layer tolerance to make a failing layer pass — re-measure and
re-freeze deliberately (and update the evidence/measurement block).
"""

from __future__ import annotations

import gzip
import hashlib
import json
import pickle
import shutil
import sys
from pathlib import Path
from unittest.mock import patch

import numpy as np
import pytest

from acp.nmr.error_model import GoodmanDP5Model
from acp.nmr.fchl import (
    C_DISTANCE,
    atom_probability_fchl,
    build_atom_representations,
    get_atomic_kernels_numpy,
    kernel_backend,
    load_atomic_reps,
    qml_kernel_available,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
GOLDENS_DIR = Path(__file__).resolve().parent / "baseline" / "nmr"
GOLDEN_PATH = GOLDENS_DIR / "fchl_golden.json"
TOLERANCES_PATH = GOLDENS_DIR / "fchl_golden_tolerances.json"
MODELS_DIR = REPO_ROOT / "src" / "acp" / "nmr" / "models"

#: Upstream revision pinned by ``src/acp/nmr/models/NOTICE.md``.
DP5_REVISION = "b6cf559007a5d13fe79654f37daf945ee1661a23"
#: sha256 pins from NOTICE.md (two pinned assets) + the exact checked-in files
#: the golden consumes (so an asset swap surfaces as a clear provenance failure
#: instead of a mysterious numeric drift).
ASSET_SHA256 = {
    "atomic_reps.gz": "bb8f798c1dd898811801a9fdd9f4bf037e434968f66e050acf3fb616a7652a65",
    "frag_reps.gz": "e5daae0f7b525632beed6cbd9b972b0be466f33e28c5cdb7efd1f1caaafb6c64",
    "folded_scaled_errors.p": "c59bd8d3218b28db0e5dde3cf70911688ce530351c45f7930a4b470bd9d200dd",
    "c_w_kde_mean_s_0.025.p": "246025abffd97e32cc405d8956deaf3fd03e7426ff688e7052340135e79dc309",
    "i_w_kde_mean_s_0.025.p": "2d523808d3859e8a48c695f5dbf8f9b9fe1fd3f02ee2dc70c8016414cf8f383e",
}

# ---------------------------------------------------------------------------
# Frozen inputs (also mirrored into the golden's ``inputs`` block for audit)
# ---------------------------------------------------------------------------

ETHANOL_SYMBOLS = ["C", "C", "O", "H", "H", "H", "H", "H", "H"]

#: Fixed ethanol geometry (all-atom, hand-frozen; not re-embedded so RDKit
#: version drift cannot change the fixture).
ETHANOL_CONFORMER_1 = [
    [-1.2435, -0.2013, 0.0000],
    [0.0000, 0.6546, 0.0000],
    [1.0899, -0.2045, 0.0000],
    [1.9073, 0.2900, 0.0000],
    [-1.3115, -0.8374, 0.8841],
    [-1.3115, -0.8374, -0.8841],
    [-2.1039, 0.4715, 0.0000],
    [0.0509, 1.2981, 0.8841],
    [0.0509, 1.2981, -0.8841],
]

#: Second conformer: gauche O-H (rotated 120 deg about C-O) + methyl rotation
#: (60 deg about C-C) of :data:`ETHANOL_CONFORMER_1`; bond lengths preserved.
ETHANOL_CONFORMER_2 = [
    [-1.2435, -0.2013, 0.0000],
    [0.0000, 0.6546, 0.0000],
    [1.0899, -0.2045, 0.0000],
    [1.0768, -0.7636, 0.7745],
    [-1.0150, -1.2682, 0.0217],
    [-1.8832, -0.0068, -0.8624],
    [-1.8085, 0.0423, 0.9024],
    [0.0509, 1.2981, 0.8841],
    [0.0509, 1.2981, -0.8841],
]

#: Third conformer: O-H rotated 240 deg about C-O, methyl rotated 120 deg
#: about C-C (same construction as :data:`ETHANOL_CONFORMER_2`).
ETHANOL_CONFORMER_3 = [
    [-1.2435, -0.2013, 0.0000],
    [0.0000, 0.6546, 0.0000],
    [1.0899, -0.2045, 0.0000],
    [1.0768, -0.7636, -0.7745],
    [-1.2902, -0.8683, -0.8624],
    [-2.1584, 0.3931, 0.0217],
    [-1.2177, -0.8160, 0.9024],
    [0.0509, 1.2981, 0.8841],
    [0.0509, 1.2981, -0.8841],
]

CARBON_ATOM_INDICES = [0, 1]

KERNEL_TRAIN_SLICE = 32
KERNEL_SELF_SLICE = 4
KERNEL_SIGMA = 0.025

KDE_SCALED_ERRORS = [0.0, 0.25, 1.0, 2.5, 5.0]
KDE_WEIGHTS_FORMULA = "np.linspace(0.001, 1.0, folded_errors.size)"

CANDIDATE_CONFORMER_CALC_SHIFTS = [[40.10, 30.20], [40.55, 29.75], [39.95, 30.30]]
CANDIDATE_EXP_SHIFTS = [40.0, 30.0]
CANDIDATE_BOLTZMANN_WEIGHTS = [0.5, 0.3, 0.2]
CANDIDATE_SINGLE_SCALED_ERRORS = [0.5, 1.0, 2.0]

FCHL_REDUCED_TRAIN_SLICE = 32

_GOLDEN_LAYER_KEYS = (
    "descriptor_c0",
    "descriptor_c1",
    "kernel_numpy_query_train32",
    "kernel_numpy_self4",
    "kde_weighted_fixed",
    "kde_zero_weight_fallback",
    "probability_per_conformer",
    "probability_single",
    "probability_per_conformer_fchl_reduced32",
)


# ---------------------------------------------------------------------------
# Layer computation (single source of truth: tests + golden generator)
# ---------------------------------------------------------------------------


def _build_reduced_models_dir(
    workdir: Path, atomic_reps: np.ndarray, folded_errors: np.ndarray
) -> Path:
    """Create a reduced DP5 model dir from a pinned slice of the real assets.

    The KDE-rescale assets (``c_w_kde_mean_s_0.025.p`` /
    ``i_w_kde_mean_s_0.025.p``) and ``frag_reps.gz`` are linked verbatim; only
    the per-atom training side is sliced (see the module docstring runtime
    note).  The folded residuals are sliced to ``2 * n_atoms`` to preserve the
    doubled kernel/residual pairing.
    """
    reduced = workdir / "reduced_models"
    if reduced.exists():
        shutil.rmtree(reduced)
    reduced.mkdir(parents=True)
    for name in ("c_w_kde_mean_s_0.025.p", "i_w_kde_mean_s_0.025.p", "frag_reps.gz"):
        (reduced / name).symlink_to(MODELS_DIR / name)
    n_atoms = FCHL_REDUCED_TRAIN_SLICE
    with (reduced / "folded_scaled_errors.p").open("wb") as fh:
        pickle.dump(folded_errors[: 2 * n_atoms], fh)
    with gzip.open(reduced / "atomic_reps.gz", "wb") as fh:
        pickle.dump(atomic_reps[:n_atoms], fh)
    return reduced


def compute_layer_values(workdir: Path) -> dict[str, object]:
    """Compute every golden layer value from the frozen inputs.

    Both the tests (via the module-scoped ``layer_values`` fixture) and
    ``tests/baseline/nmr/generate_fchl_goldens.py`` call this function, so the
    committed golden and the assertions share one computation path.
    """
    atomic_reps = load_atomic_reps()
    conf1 = np.asarray(ETHANOL_CONFORMER_1, dtype=float)
    conf2 = np.asarray(ETHANOL_CONFORMER_2, dtype=float)
    conf3 = np.asarray(ETHANOL_CONFORMER_3, dtype=float)
    reps1 = build_atom_representations(conf1, ETHANOL_SYMBOLS, CARBON_ATOM_INDICES)
    reps2 = build_atom_representations(conf2, ETHANOL_SYMBOLS, CARBON_ATOM_INDICES)
    reps3 = build_atom_representations(conf3, ETHANOL_SYMBOLS, CARBON_ATOM_INDICES)

    kernel_query = get_atomic_kernels_numpy(
        np.array([reps1[0], reps1[1]]), atomic_reps[:KERNEL_TRAIN_SLICE], [KERNEL_SIGMA]
    )
    kernel_self = get_atomic_kernels_numpy(
        atomic_reps[:KERNEL_SELF_SLICE], atomic_reps[:KERNEL_SELF_SLICE], [KERNEL_SIGMA]
    )

    model = GoodmanDP5Model()
    folded = model.folded_errors
    weights = np.linspace(0.001, 1.0, folded.size)
    dummy_reps = np.zeros((1, 5, 86))
    query_rep = reps1[0]
    with patch("acp.nmr.fchl.atom_kernel_similarities", return_value=weights):
        kde_weighted = [
            atom_probability_fchl(query_rep, se, folded, model.mean_abs_error, dummy_reps)
            for se in KDE_SCALED_ERRORS
        ]
    with patch("acp.nmr.fchl.atom_kernel_similarities", return_value=np.zeros_like(weights)):
        kde_zero_weight = [
            atom_probability_fchl(query_rep, se, folded, model.mean_abs_error, dummy_reps)
            for se in KDE_SCALED_ERRORS
        ]

    probability_per_conformer = model.probability_per_conformer(
        CANDIDATE_CONFORMER_CALC_SHIFTS, CANDIDATE_EXP_SHIFTS, CANDIDATE_BOLTZMANN_WEIGHTS
    )
    probability_single = model.probability(CANDIDATE_SINGLE_SCALED_ERRORS)

    reduced_dir = _build_reduced_models_dir(workdir, atomic_reps, folded)
    reduced_model = GoodmanDP5Model(models_dir=reduced_dir)
    conformer_reps = [[rep for rep in reps1], [rep for rep in reps2], [rep for rep in reps3]]
    # Pin the backend to numpy so the frozen golden is deterministic even on a
    # host where the compiled qml kernel is importable (qml parity is layer 2).
    with patch("acp.nmr.fchl.kernel_backend", return_value="numpy"):
        probability_fchl = reduced_model.probability_per_conformer_fchl(
            CANDIDATE_CONFORMER_CALC_SHIFTS,
            CANDIDATE_EXP_SHIFTS,
            CANDIDATE_BOLTZMANN_WEIGHTS,
            conformer_reps,
        )

    return {
        "descriptor_c0": reps1[0].tolist(),
        "descriptor_c1": reps1[1].tolist(),
        "kernel_numpy_query_train32": kernel_query.tolist(),
        "kernel_numpy_self4": kernel_self.tolist(),
        "kde_weighted_fixed": kde_weighted,
        "kde_zero_weight_fallback": kde_zero_weight,
        "probability_per_conformer": probability_per_conformer,
        "probability_single": probability_single,
        "probability_per_conformer_fchl_reduced32": probability_fchl,
    }


def golden_inputs_metadata() -> dict[str, object]:
    """The frozen-input block mirrored into the golden for audit."""
    return {
        "ethanol_symbols": list(ETHANOL_SYMBOLS),
        "ethanol_conformer_1": {"coordinates": [list(row) for row in ETHANOL_CONFORMER_1]},
        "ethanol_conformer_2": {"coordinates": [list(row) for row in ETHANOL_CONFORMER_2]},
        "ethanol_conformer_3": {"coordinates": [list(row) for row in ETHANOL_CONFORMER_3]},
        "carbon_atom_indices": list(CARBON_ATOM_INDICES),
        "kernel": {
            "train_slice": KERNEL_TRAIN_SLICE,
            "self_slice": KERNEL_SELF_SLICE,
            "sigma": KERNEL_SIGMA,
            "cut_distance": C_DISTANCE,
        },
        "kde": {
            "scaled_errors": list(KDE_SCALED_ERRORS),
            "weights_formula": KDE_WEIGHTS_FORMULA,
        },
        "candidate": {
            "conformer_calc_shifts": [list(row) for row in CANDIDATE_CONFORMER_CALC_SHIFTS],
            "exp_shifts": list(CANDIDATE_EXP_SHIFTS),
            "boltzmann_weights": list(CANDIDATE_BOLTZMANN_WEIGHTS),
            "single_scaled_errors": list(CANDIDATE_SINGLE_SCALED_ERRORS),
        },
        "fchl_reduced_train_slice": FCHL_REDUCED_TRAIN_SLICE,
    }


# ---------------------------------------------------------------------------
# Test helpers
# ---------------------------------------------------------------------------


def _load_json(path: Path) -> dict[str, object]:
    return json.loads(path.read_text(encoding="utf-8"))


def _layer_tol(layer: str) -> dict[str, float]:
    tolerances = _load_json(TOLERANCES_PATH)
    entry = tolerances["layers"][layer]  # type: ignore[index]
    return {"rtol": float(entry["rtol"]), "atol": float(entry["atol"])}


def _assert_layer_close(
    layer: str, actual: object, expected: object, tol: dict[str, float]
) -> None:
    """Assert one layer against the frozen golden with its frozen tolerance.

    The failure message names the layer and the max observed deviation so a
    breach in a lower layer cannot hide behind a passing final probability.
    """
    a = np.asarray(actual, dtype=float)
    g = np.asarray(expected, dtype=float)
    assert a.shape == g.shape, f"layer={layer}: shape {a.shape} != golden shape {g.shape}"
    dev = np.abs(a - g)
    allowed = float(tol["atol"]) + float(tol["rtol"]) * np.abs(g)
    over = dev > allowed
    if np.any(over):
        worst_flat = int(np.argmax(np.where(over, dev - allowed, -np.inf)))
        worst = np.unravel_index(worst_flat, dev.shape)
        raise AssertionError(
            f"layer={layer} FAILED vs frozen golden: max_abs_dev={float(np.max(dev)):.6e} "
            f"(frozen rtol={tol['rtol']:.1e}, atol={tol['atol']:.1e}); "
            f"{int(np.count_nonzero(over))}/{dev.size} entries exceed; "
            f"worst at {worst}: actual={a[worst]!r} golden={g[worst]!r}"
        )


@pytest.fixture(autouse=True)
def _isolate_qml_and_env(monkeypatch: pytest.MonkeyPatch) -> None:
    """Start/end each test without stubbed ``qml`` and without the numpy opt-in.

    Mirrors ``tests/test_acp_nmr_fchl.py``: a stub must never leak in, and the
    three-state backend check must observe the real environment.
    """
    for name in ("qml", "qml.fchl"):
        sys.modules.pop(name, None)
    monkeypatch.delenv("ACP_FCHL_NUMPY", raising=False)
    yield
    for name in ("qml", "qml.fchl"):
        sys.modules.pop(name, None)


@pytest.fixture(scope="module")
def layer_values(tmp_path_factory: pytest.TempPathFactory) -> dict[str, object]:
    """One computation of all layers per test module (≈8 s on the head node)."""
    return compute_layer_values(tmp_path_factory.mktemp("fchl_golden"))


# ---------------------------------------------------------------------------
# Layer 1 — FCHL descriptor
# ---------------------------------------------------------------------------


def test_layer1_descriptor_matches_frozen_golden(layer_values: dict[str, object]) -> None:
    golden = _load_json(GOLDEN_PATH)["golden"]  # type: ignore[index]
    _assert_layer_close(
        "descriptor[c0]",
        layer_values["descriptor_c0"],
        golden["descriptor_c0"],
        _layer_tol("descriptor_c0"),
    )
    _assert_layer_close(
        "descriptor[c1]",
        layer_values["descriptor_c1"],
        golden["descriptor_c1"],
        _layer_tol("descriptor_c1"),
    )


# ---------------------------------------------------------------------------
# Layer 2 — FCHL kernel (real training-set slice; qml compiled parity optional)
# ---------------------------------------------------------------------------


def test_layer2_kernel_numpy_matches_frozen_golden(layer_values: dict[str, object]) -> None:
    golden = _load_json(GOLDEN_PATH)["golden"]  # type: ignore[index]
    _assert_layer_close(
        "kernel_numpy[query_train32]",
        layer_values["kernel_numpy_query_train32"],
        golden["kernel_numpy_query_train32"],
        _layer_tol("kernel_numpy_query_train32"),
    )
    _assert_layer_close(
        "kernel_numpy[self4]",
        layer_values["kernel_numpy_self4"],
        golden["kernel_numpy_self4"],
        _layer_tol("kernel_numpy_self4"),
    )


def test_layer2_kernel_backend_three_states(monkeypatch: pytest.MonkeyPatch) -> None:
    """numpy / qml / unavailable are three explicit states — never a stub.

    With no compiled ``qml`` and no opt-in, FCHL is inactive (``""``); the
    numpy opt-in activates the pure-numpy port; a genuinely importable ``qml``
    takes precedence.  The expected branch is derived from the real
    :func:`qml_kernel_available` probe, not hardcoded, so this test records the
    environment honestly on every host.
    """
    assert "qml.fchl" not in sys.modules  # autouse isolation: no stub present
    monkeypatch.delenv("ACP_FCHL_NUMPY", raising=False)
    qml_available = qml_kernel_available()
    expected_default = "qml" if qml_available else ""
    assert kernel_backend() == expected_default
    monkeypatch.setenv("ACP_FCHL_NUMPY", "1")
    assert kernel_backend() == ("qml" if qml_available else "numpy")


@pytest.mark.skipif(
    not qml_kernel_available(),
    reason=(
        "NOT_VERIFIED: compiled qml kernel not importable — the qml parity layer "
        "was not executed; skipped, never counted as a pass "
        "(install qml on numpy<2 to verify)"
    ),
)
def test_layer2_kernel_qml_parity_vs_frozen_numpy_golden() -> None:
    """Compiled Fortran kernel vs the frozen numpy golden (qml hosts only)."""
    from qml.fchl import get_atomic_kernels

    golden = _load_json(GOLDEN_PATH)["golden"]  # type: ignore[index]
    atomic_reps = load_atomic_reps()
    reps1 = build_atom_representations(
        np.asarray(ETHANOL_CONFORMER_1, dtype=float), ETHANOL_SYMBOLS, CARBON_ATOM_INDICES
    )
    qml_kernel = get_atomic_kernels(
        np.array([reps1[0], reps1[1]]),
        atomic_reps[:KERNEL_TRAIN_SLICE],
        [KERNEL_SIGMA],
        cut_distance=C_DISTANCE,
    )
    _assert_layer_close(
        f"kernel_qml[backend={kernel_backend()}]",
        qml_kernel,
        golden["kernel_numpy_query_train32"],
        _layer_tol("kernel_qml"),
    )


# ---------------------------------------------------------------------------
# Layer 3 — weighted KDE on the full residual set with fixed weights
# ---------------------------------------------------------------------------


def test_layer3_kde_weighted_fixed_weights_matches_frozen_golden(
    layer_values: dict[str, object],
) -> None:
    golden = _load_json(GOLDEN_PATH)["golden"]  # type: ignore[index]
    _assert_layer_close(
        "kde_weighted_fixed",
        layer_values["kde_weighted_fixed"],
        golden["kde_weighted_fixed"],
        _layer_tol("kde_weighted_fixed"),
    )


def test_layer3_kde_zero_weight_fallback_matches_frozen_golden(
    layer_values: dict[str, object],
) -> None:
    golden = _load_json(GOLDEN_PATH)["golden"]  # type: ignore[index]
    _assert_layer_close(
        "kde_zero_weight_fallback",
        layer_values["kde_zero_weight_fallback"],
        golden["kde_zero_weight_fallback"],
        _layer_tol("kde_zero_weight_fallback"),
    )


# ---------------------------------------------------------------------------
# Layer 4 — candidate probability (public GoodmanDP5Model seams)
# ---------------------------------------------------------------------------


def test_layer4_probability_per_conformer_matches_frozen_golden(
    layer_values: dict[str, object],
) -> None:
    golden = _load_json(GOLDEN_PATH)["golden"]  # type: ignore[index]
    _assert_layer_close(
        "probability_per_conformer",
        layer_values["probability_per_conformer"],
        golden["probability_per_conformer"],
        _layer_tol("probability_per_conformer"),
    )


def test_layer4_probability_single_matches_frozen_golden(
    layer_values: dict[str, object],
) -> None:
    golden = _load_json(GOLDEN_PATH)["golden"]  # type: ignore[index]
    _assert_layer_close(
        "probability_single",
        layer_values["probability_single"],
        golden["probability_single"],
        _layer_tol("probability_single"),
    )


def test_layer4_probability_per_conformer_fchl_reduced_matches_frozen_golden(
    layer_values: dict[str, object],
) -> None:
    """FCHL candidate probability pipeline on the pinned training slice.

    The full 53 208-atom numpy kernel costs ~25 min per query atom; layer 2
    anchors the real kernel on the real training data and layer 3 anchors the
    full-residual KDE, so this layer can stay on the deterministic slice while
    still exercising scaling → FCHL atom probabilities → Boltzmann average →
    gmean → Bayesian rescale end to end.
    """
    golden = _load_json(GOLDEN_PATH)["golden"]  # type: ignore[index]
    _assert_layer_close(
        "probability_per_conformer_fchl[reduced32]",
        layer_values["probability_per_conformer_fchl_reduced32"],
        golden["probability_per_conformer_fchl_reduced32"],
        _layer_tol("probability_per_conformer_fchl_reduced32"),
    )


# ---------------------------------------------------------------------------
# Golden provenance / tolerance coverage audit
# ---------------------------------------------------------------------------


def test_golden_provenance_and_tolerance_coverage() -> None:
    golden = _load_json(GOLDEN_PATH)
    tolerances = _load_json(TOLERANCES_PATH)

    assert golden["schema"] == "acp_nmr_fchl_layers_golden_v1"
    assert golden["dp5_revision"] == DP5_REVISION
    assert tolerances["dp5_revision"] == DP5_REVISION
    actual_golden_sha = hashlib.sha256(GOLDEN_PATH.read_bytes()).hexdigest()
    assert tolerances["golden_sha256"] == actual_golden_sha, (
        "fchl_golden.json bytes differ from the sha256 frozen in "
        "fchl_golden_tolerances.json — re-measure and re-freeze deliberately "
        "(do not edit either file to silence a layer failure)"
    )

    for name, expected in ASSET_SHA256.items():
        actual = hashlib.sha256((MODELS_DIR / name).read_bytes()).hexdigest()
        assert actual == expected, (
            f"asset {name} drifted from dp5@{DP5_REVISION}: "
            f"expected sha256 {expected}, got {actual}; re-freeze the golden "
            "deliberately (and update NOTICE.md) instead of relaxing tolerances"
        )
    assert golden["asset_sha256"] == ASSET_SHA256

    # Golden inputs must mirror the in-test frozen inputs (drift guard).
    assert golden["inputs"] == golden_inputs_metadata()

    # Every golden layer has a frozen tolerance entry; no orphan tolerance.
    golden_keys = set(golden["golden"])  # type: ignore[arg-type]
    assert golden_keys == set(_GOLDEN_LAYER_KEYS)
    tolerance_keys = set(tolerances["layers"])
    assert golden_keys <= tolerance_keys
    assert tolerance_keys - golden_keys == {"kernel_qml"}

    # Measurement provenance must be present for the freeze to be auditable.
    measurement = tolerances["measurement"]
    assert measurement["observed_in_process_max_abs_dev"] == 0.0
    assert measurement["observed_fresh_process_max_abs_dev"] == 0.0
    for layer in sorted(golden_keys):
        entry = tolerances["layers"][layer]
        assert "rtol" in entry and "atol" in entry
        assert entry["observed_max_abs_dev"] == 0.0
    qml_entry = tolerances["layers"]["kernel_qml"]
    assert qml_entry["status"] == "NOT_VERIFIED"
